name: autoexe

on: 
    push:
        tags: ['v*']

permissions:
    contents: write

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.14'

            - name: Install dependencies
              run: | 
                pip install -r requirements.txt
                pip install pyinstaller
                
            - name: Write version file
              run: echo ${{ github.ref_name }} > version.txt

            - name: Build exe
              run: pyinstaller --onefile --add-data "version.txt;." --hidden-import async_tkinter_loop --name OW_app main.py
            
            - name: Upload to Github Releases
              uses: softprops/action-gh-release@v2
              with:
                files: dist/OW_app.exe
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}